name: Release Beta
on:
  push:
    branches:
      - beta
    paths-ignore:
      - '**.md'
      - '**.spec.js'
      - '.idea'
      - '.gitignore'
      - '.github/**'
      - '!.github/workflows/release.yml'
      - '!.github/workflows/beta.yml'
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
defaults:
  run:
    shell: 'bash'


jobs:
  draft:
    runs-on: ubuntu-latest
    outputs:
      release-note: ${{ steps.release-note.outputs.release-note }}
      release-note-json: ${{ steps.release-note.outputs.release-note-json }}
      version: ${{ steps.version.outputs.build-version }}
      draft-id: ${{ steps.draft-create.outputs.id }}
      has-updated: ${{ steps.version-updated.outputs.has-updated }}
    steps:
      - name: package.json version check
        uses: JiPaix/package-json-updated-action@v1.0.5
        id: version-updated
        with:
          path: package.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        if: steps.version-updated.outputs.has-updated == 'true'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        if: steps.version-updated.outputs.has-updated == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Get version
        if: steps.version-updated.outputs.has-updated == 'true'
        id: version
        run: echo "build-version=${{steps.version-updated.outputs.current-package-version}}-beta" >> $GITHUB_OUTPUT

      - name: Get last git tag
        if: steps.version-updated.outputs.has-updated == 'true'
        id: tag
        run: echo "last-tag=$(git describe --tags --abbrev=0 || git rev-list --max-parents=0 ${{github.ref}})" >> $GITHUB_OUTPUT

      - name: Generate release notes
        if: steps.version-updated.outputs.has-updated == 'true'
        uses: ./.github/actions/release-notes
        id: release-note
        with:
          from: ${{ steps.tag.outputs.last-tag }}
          to: ${{ github.ref }}
          include-commit-body: true
          include-abbreviated-commit: true

      - name: Waiting on All checks
        if: steps.version-updated.outputs.has-updated == 'true'
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          running-workflow-name: 'draft'

      - name: Delete outdated drafts
        if: steps.version-updated.outputs.has-updated == 'true'
        uses: hugo19941994/delete-draft-releases@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Draft
        if: steps.version-updated.outputs.has-updated == 'true'
        id: draft-create
        uses: ncipollo/release-action@v1.11.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true
          draft: true
          tag: v${{ steps.version.outputs.build-version }}
          name: v${{ steps.version.outputs.build-version }}
          body: ${{ steps.release-note.outputs.release-note }}

  upload_artifacts:
    if: needs.draft.outputs.has-updated == 'true'
    needs: [ draft ]
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
    #    To compile the application for different platforms, use:
    #    os: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18 # Need for npm >=7.7
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # The easiest way to transfer release notes to a compiled application is create `release-notes.md` in the build resources.
      # See https://github.com/electron-userland/electron-builder/issues/1511#issuecomment-310160119
      - name: Prepare release notes
        env:
          RELEASE_NOTE: ${{ needs.draft.outputs.release-note }}
        run: echo "$RELEASE_NOTE" >> ./buildResources/release-notes.md

      # Compile app and upload artifacts
      - name: Compile & release Electron app
        run: |
          npm run build
          if [ "$RUNNER_OS" == "Linux" ]; then
              npm run publish:linux
          elif [ "$RUNNER_OS" == "Windows" ]; then
              npm run publish:win
          elif [ "$RUNNER_OS" == "macOS" ]; then
              npm run publish:mac
          else
              echo "$RUNNER_OS not supported"
              exit 1
          fi
        shell: bash
        env:
          VITE_APP_VERSION: ${{ needs.draft.outputs.version }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: (DOCKER-GH) Log in to the Container registry
        if: matrix.os == 'ubuntu-latest'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: (DOCKER-GH) Extract metadata
        if: matrix.os == 'ubuntu-latest'
        id: meta
        uses: docker/metadata-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=${{ needs.draft.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ needs.draft.outputs.version }}
            type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ needs.draft.outputs.version }}
            type=semver,pattern={{major}},value=${{ needs.draft.outputs.version }}
            type=ref,event=branch

      - name: (DOCKER-GH) Build and push
        if: matrix.os == 'ubuntu-latest'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: (DOCKER-DH) Log in to the Container registry
        if: matrix.os == 'ubuntu-latest'
        uses: docker/login-action@v2
        with:
          registry: null
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: (DOCKER-DH) Extract metadata
        if: matrix.os == 'ubuntu-latest'
        id: metadh
        uses: docker/metadata-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=${{ needs.draft.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ needs.draft.outputs.version }}
            type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ needs.draft.outputs.version }}
            type=semver,pattern={{major}},value=${{ needs.draft.outputs.version }}
            type=ref,event=branch

      - name: (DOCKER-DH) Build and push
        if: matrix.os == 'ubuntu-latest'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.metadh.outputs.tags }}
          labels: ${{ steps.metadh.outputs.labels }}

  publish:
    needs: [ draft, upload_artifacts ]

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Publish release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ needs.draft.outputs.draft-id }}
      - name: Discord announce
        uses: ./.github/actions/discord-release
        with:
          discord-token: ${{ secrets.DISCORD_TOKEN }}
          discord-channel: ${{ secrets.DISCORD_CHANNEL }}
          discord-role: ${{ secrets.DISCORD_BETAROLE }}
          version: v${{ needs.draft.outputs.version }}
          release-note-json: {{ needs.draft.outputs.release-note }}
